version: '3.7'

services:
  app:
    build: .
    container_name: registerloginapp
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/register_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Charisma7

  db:
    image: postgres:latest
    container_name: POSTGRES
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: register_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Charisma7
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: