name: Deploy Dockerhub

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Restore Maven Package
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('/*.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t meshackyaro/registerloginapp:${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        run: docker push meshackyaro/registerloginapp:${{ github.sha }}

      - name: Deploy Docker Container on AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          port: 22
          script: |
            if ! command -v docker &> /dev/null; then
              echo "Docker not found. Installing Docker..."
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
            else
              echo "Docker is already installed."
            fi
            
            echo "Pulling latest Docker image from Docker Hub..."
            sudo docker pull meshackyaro/registerloginapp:${{ github.sha }}

            if [ $(sudo docker ps -q -f name=devop-container) ]; then
              echo "Stopping and removing existing container..."
              sudo docker stop devop-container
              sudo docker rm devop-container
            else
              echo "No existing container found, creating a new one..."
            fi
            
            echo "Running the new container..."
            sudo docker run -d -p 8084:8084 --name devop-container meshackyaro/registerloginapp:${{ github.sha }}

            echo "Container deployed successfully!"
            sudo docker ps
